name: ServiceNow GitHub Actions Demo

on:
  pull_request:
  push:
    branches:
      - master

jobs: 
  test:
      name: Run Tests
      runs-on: ubuntu-latest
      
      steps:
        - name: ServiceNow CI/CD Run ATF Test Suite
          uses: ServiceNow/sncicd-tests-run@1.0.0
          with:
            testSuiteSysId: 845f8b900b20220050192f15d6673aee
          env:
            nowUsername: admin
            nowPassword: Champions@21
            nowInstallInstance: https://dev102611.service-now.com/

      
